version: "3.4"


services:
  sqldata:
    environment:
      - SA_PASSWORD=Frazyecool@23
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
  
  Bazooka-Customers-Api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5080:80"

